# Base class for Survival Data Generation
SurvivalDataGenerator <- R6::R6Class("SurvivalDataGenerator",
  public = list(
    num_features = NULL,

    # Constructor
    # Description: Initializes the SurvivalDataGenerator object with the specified number of features.
    # Inputs:
    #   - num_features: Number of covariates (features) to generate for each sample.
    initialize = function(num_features) {
      self$num_features <- num_features
    },

    # Method to generate covariates X
    # Description: Generates a matrix of covariates with independent uniformly distributed values
    #              between -1 and 1. The number of covariates is specified by `num_features`.
    # Inputs:
    #   - num_samples: Number of samples to generate.
    # Outputs:
    #   - A matrix of size (num_samples x num_features) containing the generated covariates.
    sample_covariates = function(num_samples) {
      X <- matrix(runif(num_samples * self$num_features, -1, 1), nrow = num_samples)
      return(X)
    },

    # Abstract method to generate true survival times T|X
    # Description: This method should be implemented by derived classes to generate true survival times
    #              based on the covariates X and the selected survival model.
    # Inputs:
    #   - X: A matrix of covariates generated by the `sample_covariates` method.
    # Outputs:
    #   - A vector of survival times (T) for each individual.
    sample_true_survival = function(X) {
      stop("This method should be implemented by the derived class.")
    },

    # Abstract method to generate censoring times C|X
    # Description: This method should be implemented by derived classes to generate censoring times
    #              based on the covariates X and the selected model-specific censoring distribution.
    #              If true survival times T are provided, censoring times C should be sampled conditional
    #              on C > T, ensuring that censoring occurs after the event time for each individual.
    #
    # Inputs:
    #   - X: A matrix of covariates generated by the `sample_covariates` method.
    #        The censoring distribution should depend on X in a model-specific way.
    #   - T: (Optional) A vector of true survival times (T) for each individual. If provided,
    #        censoring times should be sampled to ensure that C > T for each individual.
    #
    # Outputs:
    #   - A vector of censoring times (C) for each individual. If T is provided, C will be greater
    #     than the corresponding values of T. Otherwise, censoring times should be sampled independently
    #     based on the covariates.
    sample_censoring_times = function(X, T = NULL) {
      stop("This method should be implemented by the derived class.")
    },

    # Abstract method to predict survival probabilities given failure times
    # Description: This method should be implemented by derived classes to predict survival probabilities
    #              based on the covariates X and provided failure times.
    # Inputs:
    #   - X: A data.frame of covariates generated by the `sample_covariates` method.
    #   - failure.times: A numeric vector of failure times.
    #
    # Outputs:
    #   - A list containing:
    #       - predictions: A numeric matrix of survival probabilities for each individual at each failure time.
    #       - failure.times: A numeric vector of the provided failure times.
    predict_survival = function(X, failure.times) {
      stop("This method should be implemented by the derived class.")
    },

    # Method to generate the full survival dataset
    # Description: Generates the complete survival dataset, including covariates, true survival times,
    #              censoring times, observed times, and status indicators.
    # Inputs:
    #   - num_samples: Number of samples to generate for the dataset.
    # Outputs:
    #   - A data.frame containing the generated covariates, event times, censoring times, observed times,
    #     status indicators (1 = event, 0 = censored), and covariates.
    sample_survival_data = function(num_samples) {
      # Generate covariates, true survival times, and censoring times
      X <- self$sample_covariates(num_samples)
      T <- self$sample_true_survival(X)
      C <- self$sample_censoring_times(X)

      # Determine observed time and event indicator
      time <- pmin(T, C)
      status <- as.integer(time == T)

      # Create the final dataset
      data <- data.frame(event_time = T, censoring_time = C, time = time,
                         status = status, X)
      return(data)
    }
  )
)

# Derived class for Log-Normal Survival Model
LogNormalSurvivalGenerator <- R6::R6Class("LogNormalSurvivalGenerator",
  inherit = SurvivalDataGenerator,
  public = list(

    # Method to generate true survival times based on a log-normal distribution
    # Inputs:
    #   - X: A data.frame of covariates generated by the `sample_covariates` method.
    # Outputs:
    #   - A numeric vector of survival times (T) for each individual.
    sample_true_survival = function(X) {
      num_samples <- nrow(X)
      mu_x <- log(2) + 1 + 0.55 * (X[, 1]^2 - X[, 3] * X[, 5])
      sigma_x <- 0.1 * (abs(X[, 10]) + 1)
      log_T <- rnorm(num_samples, mean = mu_x, sd = sigma_x)
      T <- exp(log_T)
      return(T)
    },

    # Internal utility to compute the censoring rate based on covariates
    # Inputs:
    #   - X: A data.frame of covariates.
    # Outputs:
    #   - A numeric vector of censoring rates for each individual.
    compute_censoring_rate = function(X) {
      return(0.05 * (1 - X[, 1]^2))
    },

    # Method to generate censoring times based on a distribution dependent on covariates X.
    # If parameter T is provided, censoring times C are sampled conditional on C > T.
    #
    # Inputs:
    #   - X: A data.frame of covariates generated by the `sample_covariates` method.
    #   - T: (Optional) A numeric vector of survival times (T) for each individual. If provided,
    #        censoring times C will be sampled to ensure that C > T for each individual.
    #
    # Outputs:
    #   - A numeric vector of censoring times (C) for each individual. If T is provided, C will be greater
    #     than the corresponding values of T. Otherwise, censoring times are sampled independently.
    sample_censoring_times = function(X, T = NULL) {
      num_samples <- nrow(X)

      # Compute censoring rates using the utility function
      censoring_rate <- self$compute_censoring_rate(X)

      # Sample censoring times from an exponential distribution
      C <- rexp(num_samples, rate = censoring_rate)

      # If true survival times T are provided, shift censoring times so that C > T
      if (!is.null(T)) {
        C <- C + T
      }

      return(C)
    },

    # Method to predict survival probabilities given failure times
    # Inputs:
    #   - X: A data.frame of covariates generated by the `sample_covariates` method.
    #   - failure.times: A numeric vector of failure times.
    #
    # Outputs:
    #   - A list containing:
    #       - predictions: A numeric matrix of survival probabilities for each individual at each failure time.
    #       - failure.times: A numeric vector of the provided failure times.
    predict_survival = function(X, failure.times) {
      # Compute censoring rates using the utility function
      censoring_rate <- self$compute_censoring_rate(X)

      # Compute survival probabilities based on the exponential distribution
      predictions <- pexp(failure.times, rate = censoring_rate, lower.tail = FALSE)
      return(list(predictions = predictions, failure.times = failure.times))
    }
  )
)


# Derived class for Weibull Survival Model
WeibullSurvivalGenerator <- R6::R6Class("WeibullSurvivalGenerator",
  inherit = SurvivalDataGenerator,
  public = list(

    # Method to generate true survival times based on a Weibull distribution
    # Inputs:
    #   - X: A matrix of covariates generated by the `sample_covariates` method.
    # Outputs:
    #   - A vector of survival times (T) for each individual.
    sample_true_survival = function(X) {
      num_samples <- nrow(X)
      shape <- 1.5  # Shape parameter
      scale <- exp(0.5 + 0.25 * X[, 1] + 0.5 * X[, 2])  # Scale parameter depends on X
      T <- rweibull(num_samples, shape = shape, scale = scale)
      return(T)
    },

    # Internal utility to compute the censoring rate based on covariates
    # Inputs:
    #   - X: A data.frame of covariates.
    # Outputs:
    #   - A numeric vector of censoring rates for each individual.
    compute_censoring_rate = function(X) {
      return(0.05 * (1 - X[, 1]^2))
    },

    # Method to generate censoring times based on a distribution dependent on covariates X.
    # If parameter T is provided, censoring times C are sampled conditional on C > T.
    #
    # Inputs:
    #   - X: A matrix of covariates generated by the `sample_covariates` method.
    #        Censoring times are influenced by specific covariates (e.g., X1).
    #   - T: (Optional) A vector of survival times (T) for each individual. If provided,
    #        censoring times C will be sampled to ensure that C > T for each individual.
    #
    # Outputs:
    #   - A vector of censoring times (C) for each individual. If T is provided, C will be greater
    #     than the corresponding values of T. Otherwise, censoring times are sampled independently
    #     based on the covariates.
    sample_censoring_times = function(X, T=NULL) {
      num_samples <- nrow(X)

      # Compute censoring rates using the utility function
      censoring_rate <- self$compute_censoring_rate(X)

      # Sample censoring times from an exponential distribution
      C <- rexp(num_samples, rate = censoring_rate)

      # If true survival times T are provided, shift censoring times so that C > T
      if (!is.null(T)) {
        C <- C + T
      }

      return(C)
    },

    # Method to predict survival probabilities given failure times
    # Inputs:
    #   - X: A data.frame of covariates generated by the `sample_covariates` method.
    #   - failure.times: A numeric vector of failure times.
    #
    # Outputs:
    #   - A list containing:
    #       - predictions: A numeric matrix of survival probabilities for each individual at each failure time.
    #       - failure.times: A numeric vector of the provided failure times.
    predict_survival = function(X, failure.times) {
      # Compute censoring rates using the utility function
      censoring_rate <- self$compute_censoring_rate(X)

      # Compute survival probabilities based on the exponential distribution
      predictions <- pexp(failure.times, rate = censoring_rate, lower.tail = FALSE)
      return(list(predictions = predictions, failure.times = failure.times))
    }

  )
)
