    # Default method to predict survival quantiles
    # Description:
    #   This method predicts survival quantiles for a given set of new data. It uses the predicted
    #   survival curves generated by the `predict_survival` method, so the `predict_survival` method
    #   must be implemented in the subclass.
    #
    # Inputs:
    #   - X: A data.frame of covariates generated by the `sample_covariates` method.
    #   - probs: A numeric vector of quantile probabilities (e.g., `c(0.25, 0.5, 0.75)` for the 25th, 50th,
    #            and 75th percentiles). These represent the survival probabilities at which the quantile
    #            survival times will be calculated.
    #
    # Outputs:
    #   - A data.frame where each row corresponds to an individual in `new_data`, and each column corresponds
    #     to one of the requested quantiles. The values in the data frame represent the survival times (in terms
    #     of time points) at which the specified survival probabilities (`probs`) are reached.
    predict_quantiles = function(X, probs = c(0.25, 0.5, 0.75), T.max = 1000, tol = 1e-3) {
        ## Predict survival curves

        ## Function to perform adaptive binary search to find the quantile time for a specific survival probability
        adaptive_binary_search <- function(individual_survival_fun, target_prob, T.max, tol) {
            lower <- 0
            upper <- T.max

            ## Check if the survival probability at T.max is still greater than the target
            if (individual_survival_fun(T.max) >= target_prob) {
                return(Inf)
            }

            while (upper - lower > tol) {
                mid <- (lower + upper) / 2
                survival_prob <- individual_survival_fun(mid)

                if (survival_prob >= target_prob) {
                    lower <- mid
                } else {
                    upper <- mid
                }
            }

            return((lower + upper) / 2)
        }

        ## Initialize a list to store quantiles for each individual
        quantiles_list <- list()

        ## Loop over each individual
        for (i in 1:nrow(X)) {
            ## Create a function that returns the survival probability at a given time for this individual
            individual_survival_fun <- function(time_point) {
                ## We calculate the survival probability for this individual at a specific time_point
                return(self$predict_survival(X[i, , drop = FALSE], failure.times = time_point)$predictions)
            }

            ## For each individual, find the survival times at the specified percentiles using adaptive binary search
            quantiles <- sapply(probs, function(p) adaptive_binary_search(individual_survival_fun, 1 - p, T.max, tol))
            quantiles_list[[i]] <- quantiles
        }

        ## Convert the list of quantiles to a data frame
        quantiles_df <- do.call(rbind, quantiles_list)
        colnames(quantiles_df) <- paste0("Q", probs * 100, "%")
        rownames(quantiles_df) <- paste0("Individual_", 1:nrow(quantiles_df))

        return(as.data.frame(quantiles_df))
    },
